### ISSUE TITLE
AttributeError: 'module' object has no attribute 'YELLOW

### ISSUE THREAD

**Issue by werdnav** [dougthor42/wafer_map#29]
The out of box example wafer_map/example.py returns "AttributeError: 'module' object has no attribute 'YELLOW'" when run on Linux Mint 17. wxPython was installed via the package manager (wx version '2.8.12.1').

Presumably you're using a newer version of wxPython? 

-a
PS: very neat tool. Thank you.

**Comment by dougthor42** [comment]
What's this? Someone is actually using my program?? Wow I feel special :-P

Let's see... Sadly I don't have access to Mint17 right now, but I may be able to check it when I get home (I can't remember if my file server runs Mint16 or Mint17...)

The current implementation uses wxPython 3.0.1.1 because I plan on porting to Python3 in the future. Let me fiddle around with some things here, perhaps try again to get the travis builds working once more.

Thanks for the report, and thanks for using the program!

**Comment by dougthor42** [comment]
In the mean time, try changing line 532 in wm_core.py from
```Python
                              LineColor=wx.YELLOW,
```
to
```Python
                              LineColor=wx.Colour(255, 255, 0, 255),
```

That code is drawing the outline of the full wafer (sans flat/notch).

You will probably also need to change any instances of `wx.RED` to `wx.Colour(255, 0, 0, 255)` and `wx.CYAN` to `wx.Colour(0, 255, 255, 255)`. These should only exist in wm_core.py, so just do a simple find-replace.

That *should* be all of the named colors I used. I'll end up putting those in `wm_constants` as wx.Colour() objects rather than named colors.

**Comment by werdnav** [comment]
yep, I use your program. Actually, I was building something similar using R when I came across your reddit thread. You're right, this type of software has a very small user base. I have a MEMS background and I'm looking at a lot of wafer probe test data at the moment. Thank's for the fix. I thought it was something along those lines. Cheers -a

**Comment by werdnav** [comment]
issue resolved
