### ISSUE TITLE
Gridlines are sometimes off by 1/2 die

### ISSUE THREAD

**Issue by dougthor42** [dougthor42/wafer_map#38]
Issue copied from localinstance.gitlab#2, 2016-04-11

Test cases:
```
Wafer Dia: 200mm
Die Size: (8.652314699206213, 8.519090170271191)
Grid Center XY: (24.24, 22.0)
Edge Excl: 0
Flat Excl: 10
```

```
Wafer Dia: 100mm
Die Size: (9.717595825602984, 8.653897938323595)
Grid Center XY: (11.24, 12.5)
Edge Excl: 0
Flat Excl: 0
```

```
Wafer Dia: 210mm
Die Size: (6.297740747141684, 5.897159765583435)
Grid Center XY: (34.24, 34.0)
Edge Excl: 5
Flat Excl: 5
```

Example:

![image](https://cloud.githubusercontent.com/assets/5386897/22607418/ad8497f2-ea0c-11e6-95d9-022abf1f6c91.png)

**Comment by henniss** [comment]
This seems to be caused by a sign error in `wm_core.draw_die_gridlines`. 

Recall that in `grid_to_rect_coord`, the `grid[i] - grid_center[i]` terms differ by a sign for `x` and `y`: 

> Adjusts for the fact that Grid +y is down while panel +y is up by
    taking ``grid_center - grid`` rather than ``grid - grid_center`` as is
    done in the X case.

`draw_die_gridlines` doesn't account for this. 

Before:
![image](https://user-images.githubusercontent.com/17056237/61007565-f9b2be80-a321-11e9-8703-24fc07b031b8.png)

After:
![image](https://user-images.githubusercontent.com/17056237/61007600-13540600-a322-11e9-9498-2fdc298d285a.png)
