### ISSUE TITLE
importing Wafer_map

### ISSUE THREAD

**Issue by jpernia101** [dougthor42/wafer_map#54]
hey not too sure if you still keep up with this project but im simply trying to creat a practice wafer map so when I try these few lines below it tell me that there is no module called WaferMapApp ..any ideas on why this might be. Excuse me if this is a noob question. im using python 3.7 btw 

```
import wafer_map


data = [(2.2,0.0, "one"),(3.2,1.0,"two"),(4.2,2.0, "three"),(5.2,3.0,"four"),(6.2, 4.0, "five")]

wafer_map.WaferMapApp(data, .5,(0,0), .5, 0, .1)
```

**Comment by dougthor42** [comment]
Yeah it's been a while since I've touched this project - I got it working well enough for my needs and then moved onto other things, haha.

I notice a couple things:
1.  You want to import `wm_app` and use that instead. See example below.
2.  I have not tested things on Python 3.7 (Python 3.4 was the hot stuff back when this was made) and I don't have an easy way to check on 3.7 yet - the best I can do is 3.6.
3.  The 2nd arg of the `WaferMapApp` class initializer should be a tuple of the die size. You've just got a single `.5` float.

```python
from wafer_map import wm_app

data = [(2.2, 0.0, "one"),
        (3.2, 1.0, "two"),
        (4.2, 2.0, "three"),
        (5.2, 3.0, "four"),
        (6.2, 4.0, "five"),
        ]
wm_app.WaferMapApp(data,
                   die_size=(0.5, 0.5),
                   )
```

However, when I run the above I get some bugs. Let me take a look at this and I'll see if I can't push out a fix.

**Comment by dougthor42** [comment]
Ah, turns out I forgot some of the API! The error I was simply user error. If you're plotting discrete data, such as the strings you have, then you must set `data_type=discrete` in the class initialization.

Since you're using such a small data set, I recommend setting (a) a small wafer diameter and (b) a small edge exclusion (the default of 5mm will take up most of your 25mm diameter wafer). Doing so will simply mean that you don't have to zoom in to see your die.

```python
wm_app.WaferMapApp(data,
                   die_size=(0.5, 0.5),
                   dia=25,
                   edge_excl=1.0,
                   data_type='discrete',
                   )
```

I hope this helps.

**Comment by dougthor42** [comment]
Oh, and the above code should net you something like:

![image](https://user-images.githubusercontent.com/5386897/45397281-2740b580-b5f4-11e8-8769-369265bfaf62.png)

**Comment by jpernia101** [comment]
man thank so much for responding ...im going to give it a shot now ...get back to you by tomorrow

**Comment by jpernia101** [comment]
Hey Doug me again. I was able to figure that out and actually plotted more die (176) to be exact so what you told me did work. However I have along ways to go with the project i'm working on and was wondering if I could email you with any further questions ? (You're email is on Pycharms Settings when you download your module) or posting them under this thread would be best ? I hope to hear back from you . I also attached an image so you can peep what your handy module did for me 
![capture](https://user-images.githubusercontent.com/21113685/45445324-88699700-b68f-11e8-8c3f-18438a25d4bc.PNG)

**Comment by dougthor42** [comment]
Glad to hear it's working! 😄 

The best way to get help will be to keep creating new GitHub issues, just like you did with this one. Each question or help topic should be a new issue. This serves a couple purposes:

1. It allows other people who might have the same problems to find the solutions.
2. It helps keep me organized.
3. If one of your questions leads to a bug, I can reference the issue when I fix it.

Please don't send directly to my email address - won't respond to that.

Thanks!

**Comment by jpernia101** [comment]
okay awesome. Obviously I'm new to this , i'll follow what you told me . Thanks !

**Comment by mannix-Lee0211** [comment]
Dear Mr.dougthor
Could you tell me how to save the mapping image to a png or other image files?
I check your code,but I can`t find any save files function.Could you tell me how to do it?
